name: Build

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build_image:
    name: Build Container Image
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Build Docker Image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile.build
          tags:
            cicd:dev
          push: false