name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build_image:
    name: Build Container Image
    runs-on: openjdk:17-jdk-alpine
    continue-on-error: true
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4


      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Build Docker Image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile.build
          tags:
            ghcr.io/${{github.repository}}/hello-fhb:${{ github.sha }}
          push: true