name: Workflow for Maven using Snyk
on: []
jobs:
  security:
    runs-on: openjdk:17-jdk-alpine
    steps:
      - uses: actions/checkout@master
      # Add this step to make the mvnw script executable
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
